swagger: '2.0'
info:
  description: API Transactions
  version: 1.0.0
  title: Transactions
  contact:
    name: Andres Jimenez
    url: 'https://github.com/afjimene'
    email: afjimene@gmail.com
  license:
    name: License
    url: 'http://unlicense.org'
host: 'localhost:8080'
basePath: /
tags:
  - name: transactions-api-controller
    description: Transactions Api Controller
paths:
  /base/v1/transactionFilter:
    post:
      tags:
        - transactions-filter-api-controller
      summary: TransactionsByFilter
      description: Transaction by filter
      operationId: transactionByFilter
      consumes:
        - application/json;charset=UTF-8
      produces:
        - application/json;charset=UTF-8
      parameters:
        - in: body
          name: body
          description: body
          required: true
          schema:
            $ref: '#/definitions/TransactionFilterRequest'
      responses:
        '200':
          description: Inquery step success
          schema:
            $ref: '#/definitions/TransactionFilterResponse'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '424':
          description: Invalid Input. please put correct request
          schema:
            $ref: '#/definitions/Errors'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Errors'
      deprecated: false
  /base/v1/transactionGroup:
    post:
      tags:
        - transactions-group-api-controller
      summary: GroupByTransactions
      description: Group by transactions
      operationId: groupByTransaction
      consumes:
        - application/json;charset=UTF-8
      produces:
        - application/json;charset=UTF-8
      parameters:
        - in: body
          name: body
          description: body
          required: true
          schema:
            $ref: '#/definitions/TransactionGroupRequest'
      responses:
        '200':
          description: Inquery step success
          schema:
            $ref: '#/definitions/TransactionGroupResponse'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '424':
          description: Invalid Input. please put correct request
          schema:
            $ref: '#/definitions/Errors'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Errors'
      deprecated: false
  /base/v1/transactionList:
    post:
      tags:
        - transactions-list-api-controller
      summary: Transactions
      description: Transaction in the account
      operationId: transactionList
      consumes:
        - application/json;charset=UTF-8
      produces:
        - application/json;charset=UTF-8
      parameters:
        - in: body
          name: body
          description: body
          required: true
          schema:
            $ref: '#/definitions/TransactionListRequest'
      responses:
        '200':
          description: Inquery step success
          schema:
            $ref: '#/definitions/TransactionListResponse'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '424':
          description: Invalid Input. please put correct request
          schema:
            $ref: '#/definitions/Errors'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Errors'
      deprecated: false
definitions:
  ErrorDetail:
    type: object
    required:
      - code
      - detail
      - id
      - source
      - status
      - title
    properties:
      code:
        type: string
      detail:
        type: string
      id:
        type: string
      source:
        type: string
      status:
        type: string
      title:
        type: string
    title: ErrorDetail
  Errors:
    type: object
    required:
      - errors
    properties:
      errors:
        type: array
        items:
          $ref: '#/definitions/ErrorDetail'
    title: Errors
  TransactionFilterRequest:
    type: object
    properties:
      counterpartyName:
        type: string
      transactionAmount:
        type: number
        format: double
      transactionType:
        type: string
    title: TransactionFilterRequest
  TransactionFilterResponse:
    type: object
    title: TransactionFilterResponse
  TransactionGroupRequest:
    type: object
    title: TransactionGroupRequest
  TransactionGroupResponse:
    type: object
    title: TransactionGroupResponse
  TransactionListRequest:
    type: object
    title: TransactionListRequest
  TransactionListResponse:
    type: object
    title: TransactionListResponse
